/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientnt;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 * This class is the interface that helps the user to log in to his account.
 *
 * @author Gewrgios Kirmitsakis
 */
public class GUIforLogInOn extends javax.swing.JFrame {

    /**
     * Creates new form GUIforLogIn.
     */
    public GUIforLogInOn() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {}
        initComponents();
        groupButton();
        jRadioButton1.setSelected(true);
        password0T.setEchoChar((char) 0);
        password1T.setEchoChar((char) 0);
        welcomeText.setText("Please complete all fields to Log In/On:");
        jpanelCreator();
    }

    /**
     * creates the group of the 2 buttons logIn and register.
     */
    private void groupButton() {
        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(jRadioButton1);
        bg1.add(jRadioButton2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        password1 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        userName1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        userNameT = new javax.swing.JTextField();
        password0T = new javax.swing.JPasswordField();
        password0L = new javax.swing.JLabel();
        password1L = new javax.swing.JLabel();
        password1T = new javax.swing.JPasswordField();
        fieldsText = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cancelB = new javax.swing.JButton();
        logInOnB = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        quitB = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        password1.setText("Password:");

        jMenuItem1.setText("jMenuItem1");

        userName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userName1.setText("Username:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(340, 296));

        welcomeText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeText.setText("#######");

        userName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userName.setText("Username:          ");

        userNameT.setText("Enter your username.");
        userNameT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameTFocusLost(evt);
            }
        });

        password0T.setText("Enter your password.");
        password0T.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password0TFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password0TFocusLost(evt);
            }
        });

        password0L.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        password0L.setText("Password:           ");

        password1L.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        password1L.setText("Verify Password:");
        password1L.setOpaque(true);

        password1T.setText("Enter your password.");
        password1T.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password1TFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password1TFocusLost(evt);
            }
        });

        fieldsText.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        fieldsText.setForeground(new java.awt.Color(255, 0, 0));
        fieldsText.setText("*All Fields are neccessary.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldsText)
                            .addComponent(welcomeText))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(password1L, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(password0L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userNameT)
                                .addComponent(password0T, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(password1T, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeText)
                .addGap(4, 4, 4)
                .addComponent(fieldsText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password0T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password0L))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password1T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password1L))
                .addContainerGap())
        );

        cancelB.setText("Cancel");
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });

        logInOnB.setText("Log In");
        logInOnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInOnBActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Log In");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        jRadioButton2.setText("Log On");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logInOnB, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelB, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logInOnB)
                            .addComponent(cancelB)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)))
                .addGap(5, 5, 5))
        );

        jLabel1.setText("IP of server:");

        jLabel2.setText("Port of server:");

        jTextField1.setText("Enter IP.");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jTextField2.setText("Enter Port.");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        File.setText("File");

        quitB.setText("Quit");
        quitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBActionPerformed(evt);
            }
        });
        File.add(quitB);

        jMenuBar1.add(File);

        jMenu2.setText("Help");

        jMenuItem2.setText("Help");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Clears the text fields
     *
     * @param b true if it needs to clear some fields
     */
    private void clearer(boolean b) {
        if (b) {
            jTextField1.setText("Enter IP.");
            jTextField2.setText("Enter Port.");
            userNameT.setText("Enter your username.");
        }
        password0T.setText("Enter your password.");
        password0T.setEchoChar((char) 0);
        password1T.setText("Enter your password.");
        password1T.setEchoChar((char) 0);
    }

    private void logInOnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInOnBActionPerformed
        ClientNT temp = new ClientNT();
        try {
            if (userNameT.getText().contains(" ") || password0T.getText().contains(" ")) { //den theloume space sta fields giati me space xorizonte oi metablites sto userMap.

                JOptionPane.showMessageDialog(null, "Please don't put space in the fields.",
                        "Error message", JOptionPane.PLAIN_MESSAGE);
            } else if (jTextField1.getText().contains(" ") || jTextField2.getText().contains(" ")) {
                JOptionPane.showMessageDialog(null, "Please give IP and port.",
                        "Error message", JOptionPane.PLAIN_MESSAGE);
                jTextField1.setText("Enter IP.");
                jTextField2.setText("Enter Port.");
            } else {
                if (jRadioButton1.isSelected()) { // logIn

                    if (temp.logIn(userNameT.getText(), password0T.getText(), jTextField1.getText(), jTextField2.getText())) {
                        GUImainBody mainGUI = new GUImainBody(userNameT.getText(), password0T.getText(), temp.dataGetter(), temp);
                        mainGUI.setLocationRelativeTo(null);
                        mainGUI.setVisible(true);
                        dispose();
                    } else { // log in failed
                        JOptionPane.showMessageDialog(null, "No account with this input.",
                                "Error message", JOptionPane.PLAIN_MESSAGE);
                        clearer(true);
                    }
                } else { // register
                    if (password0T.getText().equals(password1T.getText())) {
                        if (temp.register(userNameT.getText(), password0T.getText(), jTextField1.getText(), jTextField2.getText())) {
                            GUImainBody mainGUI = new GUImainBody(userNameT.getText(), password0T.getText(), temp.dataGetter(), temp);
                            mainGUI.setLocationRelativeTo(null);
                            mainGUI.setVisible(true);
                            dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "There is already an account with\n"
                                    + "this input, plz try agien.", "Error message", JOptionPane.PLAIN_MESSAGE);
                            clearer(true);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Put same password.", "Error message", JOptionPane.PLAIN_MESSAGE);
                        clearer(false);
                    }
                }
            }
        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Put number for Port.", "Error message", JOptionPane.PLAIN_MESSAGE);
            clearer(true);
        }
    }//GEN-LAST:event_logInOnBActionPerformed

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        JOptionPane.showMessageDialog(null, "Not yet implimented.",
                "Help Box", JOptionPane.INFORMATION_MESSAGE);
//        GUI temp = new GUI(); //ama patisei o xristis cancel tote to programa ton epistrefei sto arxiko GUI
//        temp.setLocationRelativeTo(null);
//        temp.setVisible(true);
//        dispose();
    }//GEN-LAST:event_cancelBActionPerformed

    private void quitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitBActionPerformed

    private void password0TFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password0TFocusGained
        if (password0T.getText().equals("Enter your password.")) { // ama auto to field to kanei focus o xristis to text tha e3afanistei
            password0T.setText("");
            password0T.setEchoChar('*'); //oti grafei o xristis tha emfanizete se ***
        }
    }//GEN-LAST:event_password0TFocusGained

    private void userNameTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTFocusGained
        if (userNameT.getText().equals("Enter your username.")) {
            userNameT.setText("");
        }
    }//GEN-LAST:event_userNameTFocusGained

    private void userNameTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTFocusLost
        if (userNameT.getText().equals("")) { //ama xathei to focus apo to field kai den exei xrapsei tipota o xristis tote 
            userNameT.setText("Enter your username."); // grafete auto to text
        }
    }//GEN-LAST:event_userNameTFocusLost

    private void password0TFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password0TFocusLost
        if (password0T.getText().equals("")) {
            password0T.setText("Enter your password.");
            password0T.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_password0TFocusLost

    private void password1TFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password1TFocusGained
        if (password1T.getText().equals("Enter your password.")) {
            password1T.setText("");
            password1T.setEchoChar('*');
        }
    }//GEN-LAST:event_password1TFocusGained

    private void password1TFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password1TFocusLost
        if (password1T.getText().equals("")) {
            password1T.setText("Enter your password.");
            password1T.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_password1TFocusLost

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(null, "Enter your username and password.",
                "Help Box", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        jpanelCreator();
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        jpanelCreator();
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        if (jTextField1.getText().equals("Enter IP.")) {
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if (jTextField1.getText().equals("")) {
            jTextField1.setText("Enter IP.");
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        if (jTextField2.getText().equals("Enter Port.")) {
            jTextField2.setText("");
        }
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        if (jTextField2.getText().equals("")) {
            jTextField2.setText("Enter Port.");
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        char c = evt.getKeyChar();
        if (!(c >= 48 && c <= 57)) {
            evt.consume(); // ignore event
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jpanelCreator() {
        if (jRadioButton1.isSelected()) {
            password1L.setVisible(false);
            password1T.setVisible(false);
            logInOnB.setText("Log In"); //allazei kai to text merikwn koumpiwn
        } else { // ama thelei na kanei register tote allazoun aplos merika text
            password1L.setVisible(true);
            password1T.setVisible(true);
            logInOnB.setText("Register");
        }
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIforLogInOn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIforLogInOn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIforLogInOn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIforLogInOn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIforLogInOn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu File;
    private javax.swing.JButton cancelB;
    private javax.swing.JLabel fieldsText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton logInOnB;
    private javax.swing.JLabel password0L;
    private javax.swing.JPasswordField password0T;
    private javax.swing.JLabel password1;
    private javax.swing.JLabel password1L;
    private javax.swing.JPasswordField password1T;
    private javax.swing.JMenuItem quitB;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel userName1;
    private javax.swing.JTextField userNameT;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
