/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientnt;

import message.Email;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 * Graphical user interface for the emails.
 *
 * @author Gewrgios Kirmitsakis
 */
public class GUImainBody extends javax.swing.JFrame {

    ClientNT client;
    private final String userNameS;
    private String passwordS;
    private List<Email> dataLE;
    private List<String> dataNamesLS;
    private int lastValueSelectedI;
    Refresher kl;
//    private Font font;

    /**
     * Creates new form GUImainBody
     *
     * @param userNameS
     * @param passwordS
     * @param dataAll
     * @param client
     */
    public GUImainBody(String userNameS, String passwordS, List<Email> dataAll, ClientNT client) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
        }
        initComponents();
//        jButton2.setEnabled(false);
//        jButton3.setEnabled(false);
        this.client = client;
        this.userNameS = userNameS;
        jLabel6.setText(userNameS);
        this.passwordS = passwordS;
        lastValueSelectedI = -1;
        changePasswordB.setEnabled(false);
//        font = new Font("Times New Roman",Font.BOLD,16);
//        setFont(font);

        emailList(dataAll);
        kl = new Refresher(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sentToT = new javax.swing.JTextField();
        subjectT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainBodyT = new javax.swing.JTextArea();
        sentB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        deleteB = new javax.swing.JButton();
        editB = new javax.swing.JButton();
        refreshB = new javax.swing.JButton();
        showB = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        logOutB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        changePasswordB = new javax.swing.JMenuItem();
        deleteAccountB = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Wellcome to myEmailClient");

        jLabel2.setText("Sent to:");

        jLabel3.setText("Subject:");

        jLabel4.setText("Main:");

        mainBodyT.setColumns(20);
        mainBodyT.setRows(5);
        jScrollPane1.setViewportView(mainBodyT);

        sentB.setText("Sent");
        sentB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sentB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sentToT)
                    .addComponent(subjectT)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sentToT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(subjectT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sentB))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("New Message", jPanel1);

        jTextField3.setEditable(false);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        deleteB.setText("Delete");
        deleteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBActionPerformed(evt);
            }
        });

        editB.setText("Edit");
        editB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBActionPerformed(evt);
            }
        });

        refreshB.setText("Refresh");
        refreshB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBActionPerformed(evt);
            }
        });

        showB.setText("Respond");
        showB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBActionPerformed(evt);
            }
        });

        jList2.setName(""); // NOI18N
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jList2);

        jTextField4.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refreshB, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editB)
                            .addComponent(deleteB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(refreshB)
                            .addComponent(showB)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("All Messages", jPanel2);

        jLabel5.setText("Loged in as:");

        logOutB.setText("log out");
        logOutB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBActionPerformed(evt);
            }
        });

        jLabel6.setText("someone");

        jMenu1.setText("File");

        changePasswordB.setText("Change password");
        jMenu1.add(changePasswordB);

        deleteAccountB.setText("Delete account");
        deleteAccountB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountBActionPerformed(evt);
            }
        });
        jMenu1.add(deleteAccountB);

        jMenuItem1.setText("Close server");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(255, 255, 255)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logOutB)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(logOutB)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBActionPerformed
        GUIforLogInOn mainGUI = new GUIforLogInOn();
        mainGUI.setLocationRelativeTo(null);
        mainGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOutBActionPerformed

    private void sentBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentBActionPerformed
        if (sentToT.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No sent andress.",
                    "Error message", JOptionPane.PLAIN_MESSAGE);
        } else if (sentToT.getText().equals(userNameS)) {
            JOptionPane.showMessageDialog(null, "You cant sent email to yourself.",
                    "Error message", JOptionPane.PLAIN_MESSAGE);
        } else {//boolean isNew, String senter, String reciever, String subject, String mainBody, int howManyEmails
            Email mail = new Email(true, userNameS, sentToT.getText(), subjectT.getText(), mainBodyT.getText());
            if (client.sentMessage(mail)) {
                dataLE.add(mail);
                dataNamesLS.add(mail.subjectGetter());
                lastValueSelectedI = jList2.getSize().height;
                emailList();
                clearer();
                jTabbedPane1.setSelectedIndex(1);
                JOptionPane.showMessageDialog(null, "The message sented successfully.",
                        "Info-chan message", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Failed to sent the message, plz try again.",
                        "Error message", JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_sentBActionPerformed

    private void deleteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBActionPerformed
        Object selectedValue = jList2.getSelectedValue();
        if (selectedValue == null) {

        } else {
//            if (client.deleteEmail(userNameS, dataLE.get(dataNamesLS.indexOf(selectedValue.toString())))) {
            if (client.deleteEmail(userNameS, dataNamesLS.indexOf(selectedValue.toString()))) {
                dataLE.remove(dataNamesLS.indexOf(selectedValue.toString()));
                dataNamesLS.remove(selectedValue.toString());
                emailList();
                clearer();
                JOptionPane.showMessageDialog(null, "The message deleted successfully.",
                        "Info-chan message", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Failed to delete the message, plz try again.",
                        "Error message", JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteBActionPerformed

    private void showBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBActionPerformed
        Object selectedValue = jList2.getSelectedValue();
        if (selectedValue == null) {

        } else {
            String[] s = jTextField4.getText().split(" -> ");
            if (s[1].equals(userNameS)) {
                sentToT.setText(s[0]);
            } else {
                sentToT.setText(s[0]);
            }
            subjectT.setText("RE: " + jTextField3.getText());
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_showBActionPerformed

    private void editBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        subjectT.setText(jTextField3.getText());
        mainBodyT.setText(jTextArea2.getText());
    }//GEN-LAST:event_editBActionPerformed

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        Object selectedValue = jList2.getSelectedValue();
        if (selectedValue == null) {

        } else {
            String selectedValueS = selectedValue.toString();
            jTextField4.setText(dataLE.get(dataNamesLS.indexOf(selectedValueS)).senterGetter() + " -> " + dataLE.get(dataNamesLS.indexOf(selectedValue.toString())).recieverGetter());
            jTextField3.setText(dataLE.get(dataNamesLS.indexOf(selectedValueS)).subjectGetter());
            jTextArea2.setText(dataLE.get(dataNamesLS.indexOf(selectedValueS)).mainBodyGetter());
            if (dataLE.get(dataNamesLS.indexOf(selectedValueS)).isNewBGetter() == true) {
                setReader(selectedValueS);
            }
        }
    }//GEN-LAST:event_jList2ValueChanged

    private void refreshBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBActionPerformed
        if (!client.refresh(userNameS)) {
            emailList(client.dataGetter());
        }
    }//GEN-LAST:event_refreshBActionPerformed

    private void deleteAccountBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountBActionPerformed
        Object[] options = {"CANCEL", "YES"};
        int i = JOptionPane.showOptionDialog(null, "Do you want to Delete your Acoount", "Warning", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        switch (i) {
            case 0:
                break;
            case 1:
                if (client.deleteAccount(userNameS)) {
                    GUIforLogInOn temp = new GUIforLogInOn();
                    temp.setLocationRelativeTo(null);
                    temp.setVisible(true);
                    dispose();
                    JOptionPane.showMessageDialog(null, "Your account deleted succesfully.",
                            "Info-chan message", JOptionPane.PLAIN_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to delete your account, plz try again.",
                            "Error message", JOptionPane.PLAIN_MESSAGE);
                }
                break;
        }
    }//GEN-LAST:event_deleteAccountBActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        kl.refreshingThreadCreator();
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        client.closer();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void refreshersMethode() {
        if (!client.refresh(userNameS)) {
            emailList(client.dataGetter());
        }
    }

    private void setReader(String selectedValueS) {
        Email mail = dataLE.get(dataNamesLS.indexOf(selectedValueS));
        mail.isNewSetter(false);
        client.readThatMail(userNameS, dataNamesLS.indexOf(selectedValueS));
        emailList(dataLE);
//        jList2.setSelectedIndex(dataNamesLS.indexOf(selectedValueS));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUImainBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUImainBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUImainBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUImainBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUImainBody("Someone", "pass", null, null).setVisible(true);
            }
        });
    }

    private void clearer() {
        jTextField4.setText("");
        jTextField3.setText("");
        jTextArea2.setText("");
        sentToT.setText("");
        subjectT.setText("");
        mainBodyT.setText("");
    }

    private void emailList() {
        DefaultListModel listModel = new DefaultListModel();
        for (String s : dataNamesLS) {
            listModel.addElement(s);
        }
        jList2.setModel(listModel);
        if (lastValueSelectedI == -1) {
            if (!jList2.isSelectionEmpty()) {
                jList2.setSelectedIndex(0);
            }
        } else {
            jList2.setSelectedIndex(lastValueSelectedI);
        }
//        jPanel2.repaint();
//        jPanel2.revalidate();
    }

    private void emailList(List<Email> dataAll) {
        Object selectedValue = jList2.getSelectedValue();
        if (selectedValue != null) {
            lastValueSelectedI = dataNamesLS.indexOf(selectedValue.toString());
        }
//        System.out.println("edw");
//        client= new ClientNT();
//        this.dataLE = new ArrayList<>();
        this.dataLE = dataAll;
//        for (Email loula : dataLE) {
//            System.out.println(loula.soutAllGetter());
//        }
        this.dataNamesLS = new ArrayList<>();
        for (int i = 0; dataAll.size() - 1 >= i; i++) {
            if (dataAll.get(i).isNewBGetter() == true) {
                this.dataNamesLS.add("->" + dataAll.get(i).subjectGetter());
            } else {
                this.dataNamesLS.add("  " + dataAll.get(i).subjectGetter());
            }
        }
        jList2.removeAll();
        emailList();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem changePasswordB;
    private javax.swing.JMenuItem deleteAccountB;
    private javax.swing.JButton deleteB;
    private javax.swing.JButton editB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton logOutB;
    private javax.swing.JTextArea mainBodyT;
    private javax.swing.JButton refreshB;
    private javax.swing.JButton sentB;
    private javax.swing.JTextField sentToT;
    private javax.swing.JButton showB;
    private javax.swing.JTextField subjectT;
    // End of variables declaration//GEN-END:variables
}
